USE [TestIndicies]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[UpdateTextCountRows](
	[Partition] [tinyint] NOT NULL,
	[Text] [varbinary](16) NOT NULL,
	[Count] [int] NOT NULL,
	[CountStartedOn] [datetime2](0) NOT NULL,
 CONSTRAINT [PK_UpdateTextCountRows] PRIMARY KEY CLUSTERED 
(
	[Partition] ASC, [Text] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[InsertNewTextCountRows](
	[Partition] [tinyint] NOT NULL,
	[Text] [varbinary](16) NOT NULL,
	[Count] [int] NOT NULL,
	[CountStartedOn] [datetime2](0) NOT NULL,
 CONSTRAINT [PK_InsertNewTextCountRows] PRIMARY KEY CLUSTERED 
(
	[Partition] ASC, [Text] ASC, [CountStartedOn] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO